CREATE TABLE IF NOT EXISTS LIBRARIAN (
    Tab_num CHAR(10) NOT NULL,
    L_Surname VARCHAR(40) NOT NULL,
    L_Name VARCHAR(30) NOT NULL,
    L_Middle_name VARCHAR(30) NULL,
    PRIMARY KEY (Tab_num)
);

CREATE TABLE IF NOT EXISTS LIBRARIAN_PHONE (
    L_Phone_num VARCHAR(20) NOT NULL,
    L_Tab_num CHAR(10) NOT NULL,
    PRIMARY KEY(L_Phone_num),
    FOREIGN KEY(L_Tab_num)
        REFERENCES LIBRARIAN(Tab_num)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS LIBRARIAN_EMAIL (
    L_Email VARCHAR(50) NOT NULL,
    L_Tab num CHAR(10) NOT NULL,
    PRIMARY KEY(L_Email),
    FOREIGN KEY(L_Tab_num)
        REFERENCES LIBRARIAN(Tab_num)
        ON DELETE CASCADE
);